import type { Metadata } from 'next';
import { Geist_Mono, Lato, Poppins } from 'next/font/google';

import { Footer } from '@components/shared/blocks/globals/footer';
import { Header } from '@components/shared/blocks/globals/header';

import { payload } from '@lib/payload';

import '@styles/globals.css';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const lato = Lato({
  variable: '--font-lato',
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [header, footer] = await Promise.all([
    payload.findGlobal({ slug: 'header' }),
    payload.findGlobal({ slug: 'footer' }),
  ]);

  return (
    <html lang="en">
      <body className={`${poppins.variable} ${lato.variable} ${geistMono.variable} antialiased dark:bg-black`}>
        <Header siteName={header?.siteName} menu={header?.menu} actions={header?.actions} />
        {children}
        <Footer copyright={footer?.copyright} menu={footer?.menu} socialLinks={footer?.socialLinks} />
      </body>
    </html>
  );
}
