services:
  db:
    image: postgres:16
    container_name: ${APP_NAME}-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: ${APP_NAME}-adminer
    ports:
      - '${ADMINER_PORT}:8080'
  bucket-storage:
    image: minio/minio
    container_name: ${APP_NAME}-bucket
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
  mailpit:
    image: axllent/mailpit
    container_name: ${APP_NAME}-mailpit
    volumes:
      - mailpit-data:/data
    ports:
      - 8025:8025
      - '${SMTP_PORT}:1025'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pgdata:
  minio-data:
  mailpit-data:
