services:
  db:
    image: postgres:16
    container_name: ${APP_NAME}-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: ${APP_NAME}-adminer
    restart: always
    ports:
      - '${ADMINER_PORT}:8080'
  bucket-storage:
    image: minio/minio
    container_name: ${APP_NAME}-bucket
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  pgdata:
  minio-data:
