name: Discord Commit Notifier

on:
  push:
    branches:
      - 'main'
      - 'develop'
  workflow_dispatch:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"New commit by $GITHUB_ACTOR on branch ${GITHUB_REF#refs/heads/}\nCommit: $GITHUB_SHA\"}" \
            $DISCORD_WEBHOOK_URL
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
